resolution: 256
name: "PDG"
ckpt_path: 'exps/SPRINT_XL_ImageNet256/checkpoints/model_1.safetensors' # put your own ckpt path here

seed:
  global_seed: 888

precision:
  tf32: true   # By default, use TF32 matmuls (recommended for Ampere GPUs)

compile:
  enabled: true
  mode: default
  backend: inductor
  fullgraph: false
  dynamic: false

profile:
  enabled: true

model:
  arch: "SiT"
  type: 'XL'
  network_config:
    context_size: 32
    patch_size: 2
    in_channels: 4
    num_classes: 1000
    class_dropout_prob: 0.1
    use_swiglu_large: true
    q_norm: RMSNorm
    k_norm: RMSNorm
    representation_align: false
    representation_depth: 8
    encoder_depth: 2
    middle_depth: 24
    decoder_depth: 2
    use_mask_restore: true
    cfg_mask_prob: 0.1
    residual_type: concat_linear

sampling:
  per_proc_batch_size: 50
  num_fid_samples: 50000

  # Sampling-related hyperparameters
  mode: "sde"
  path_type: "linear"       # choices: [linear, cosine]
  prediction: "v"
  num_steps: 250
  cfg_scale: 3.0
  guidance_low: 0.0
  guidance_high: 1.0
  path_drop_guidance: true